"""Agregando claves foráneas en tablas

Revision ID: 4032b8b05663
Revises: 
Create Date: 2025-03-12 12:15:12.193683

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4032b8b05663'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_appointments_clients', type_='foreignkey')
        batch_op.drop_constraint('fk_appointments_vehicles', type_='foreignkey')
        batch_op.create_foreign_key(None, 'clients', ['clients_id'], ['id'])

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_chat_messages_clients', type_='foreignkey')
        batch_op.drop_constraint('fk_chat_messages_employees', type_='foreignkey')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint('fk_clients_users', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['users_id'], ['id'])

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint('fk_employees_users', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['users_id'], ['id'])

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint('fk_invoices_order', type_='foreignkey')
        batch_op.drop_constraint('fk_invoices_clients', type_='foreignkey')
        batch_op.create_foreign_key(None, 'repair_order', ['order_id'], ['id'])
        batch_op.create_foreign_key(None, 'clients', ['clients_id'], ['id'])

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('response_text',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('response_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.drop_constraint('fk_messages_users', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['users_id'], ['id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('payment_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('Pendiente', 'Cobrado'),
               type_=sa.String(length=10),
               nullable=True)
        batch_op.drop_constraint('fk_payments_clients', type_='foreignkey')
        batch_op.drop_constraint('fk_payments_invoices', type_='foreignkey')
        batch_op.create_foreign_key(None, 'invoices', ['invoices_id'], ['id'])
        batch_op.create_foreign_key(None, 'clients', ['clients_id'], ['id'])

    with op.batch_alter_table('repair_detail', schema=None) as batch_op:
        batch_op.alter_column('unit_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('subtotal',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.drop_constraint('fk_repair_detail_repair_order', type_='foreignkey')
        batch_op.drop_constraint('fk_repair_detail_spare_parts', type_='foreignkey')
        batch_op.create_foreign_key(None, 'repair_order', ['repair_order_id'], ['id'])

    with op.batch_alter_table('repair_order', schema=None) as batch_op:
        batch_op.alter_column('estimated_delivery',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.drop_index('fk_repair_orders_details')
        batch_op.drop_constraint('fk_repair_order_clients', type_='foreignkey')
        batch_op.drop_constraint('fk_repair_order_vehicles', type_='foreignkey')
        batch_op.create_foreign_key(None, 'clients', ['clients_id'], ['id'])
        batch_op.create_foreign_key(None, 'repair_detail', ['repair_detail_id'], ['id'])
        batch_op.create_foreign_key(None, 'vehicles', ['vehicles_id'], ['id'])

    with op.batch_alter_table('session_tokens', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['token'])
        batch_op.drop_constraint('fk_session_tokens_users', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['users_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_user_type', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_types', ['user_type_id'], ['id'])
        batch_op.drop_column('registration_date')

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index('client_id')
        batch_op.create_foreign_key(None, 'clients', ['clients_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('client_id', ['clients_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_date', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_users_user_type', 'user_types', ['user_type_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('session_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_session_tokens_users', 'users', ['users_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('repair_order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_repair_order_vehicles', 'vehicles', ['vehicles_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key('fk_repair_order_clients', 'clients', ['clients_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_index('fk_repair_orders_details', ['repair_detail_id'], unique=False)
        batch_op.alter_column('estimated_delivery',
               existing_type=mysql.DATETIME(),
               nullable=False)

    with op.batch_alter_table('repair_detail', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_repair_detail_spare_parts', 'spare_parts_inventory', ['sparePartsInventory_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key('fk_repair_detail_repair_order', 'repair_order', ['repair_order_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.alter_column('subtotal',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('unit_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_payments_invoices', 'invoices', ['invoices_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key('fk_payments_clients', 'clients', ['clients_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.alter_column('status',
               existing_type=sa.String(length=10),
               type_=mysql.ENUM('Pendiente', 'Cobrado'),
               nullable=False)
        batch_op.alter_column('payment_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_messages_users', 'users', ['users_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.alter_column('response_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('response_text',
               existing_type=mysql.TEXT(),
               nullable=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_invoices_clients', 'clients', ['clients_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key('fk_invoices_order', 'repair_order', ['order_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_employees_users', 'users', ['users_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_clients_users', 'users', ['users_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_chat_messages_employees', 'employees', ['employees_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key('fk_chat_messages_clients', 'clients', ['clients_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_appointments_vehicles', 'vehicles', ['vehicles_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key('fk_appointments_clients', 'clients', ['clients_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###
