"""Corrección de claves foráneas en chat_messages

Revision ID: ec0d90a32691
Revises: 
Create Date: 2025-03-21 11:53:01.716425

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ec0d90a32691'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_chat_messages_employees', type_='foreignkey')
        batch_op.drop_constraint('fk_chat_messages_clients', type_='foreignkey')
        batch_op.create_foreign_key('fk_chat_messages_clients', 'clients', ['clients_id'], ['id'])
        batch_op.create_foreign_key('fk_chat_messages_employees', 'employees', ['employees_id'], ['id'])

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('repair_detail', schema=None) as batch_op:
        batch_op.drop_constraint('fk_repair_detail_spare_parts', type_='foreignkey')

    with op.batch_alter_table('repair_detail', schema=None) as batch_op:
        batch_op.drop_index('fk_repair_detail_spare_parts')
        
        batch_op.create_foreign_key(
            'fk_repair_detail_spare_parts',
            'spare_parts_inventory',
            ['sparePartsInventory_id'],
            ['id'],
            onupdate='CASCADE',
            ondelete='CASCADE'
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repair_detail', schema=None) as batch_op:
        batch_op.drop_constraint('fk_repair_detail_spare_parts', type_='foreignkey')
        batch_op.create_index('fk_repair_detail_spare_parts', ['sparePartsInventory_id'], unique=False)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_chat_messages_employees', type_='foreignkey')
        batch_op.drop_constraint('fk_chat_messages_clients', type_='foreignkey')
        batch_op.create_foreign_key('fk_chat_messages_clients', 'clients', ['clients_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key('fk_chat_messages_employees', 'employees', ['employees_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###
